hydrodynamics:
    north: 1
    east: 2
    yaw: 0 
    yaw_ref: 45 
    speed: 5
    speed_ref: 7
    yaw_rate: 0
    dt: 0.0002

physics:
    mass: 50000000000 
    linear_damping_coeff: 500000000
    length: 20
    width: 3

devices:
     - name: RADAR
       driver: maritime.regulation.colreg.Evaluator
       args: sample.frequency=1
