packages:
  modules:  # Kernel subsystem services
     - name: RPCBroker
       module: cos.subsystem.network.RPCBroker
       config: transport=cos.core.network.RPCZMQTransport

     - name: NetworkManager
       module: cos.subsystem.network.NetworkManager
       config: 

     - name: DataManager
       module: cos.subsystem.data.DataManager
       config: storage=$(DB)/data/maritime.workingset.s3db schema=$(CONFIG)/data/maritime.xml rowstart=1000

     - name: World
       module: cos.subsystem.world.World
       config: 
