
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : World.idl
// Function         : ROVCore - Simulation World
/////////////////////////////////////////////////////////////////////////////////////////


interface World
{
	string 	describe( string id );
};

