
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : Land.idl
// Function         : ROVCore - Simulation Land
/////////////////////////////////////////////////////////////////////////////////////////


interface Land
{
	object 	describe( string id );
};

