
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : Port.idl
// Function         : ROVCore - Simulation Port
/////////////////////////////////////////////////////////////////////////////////////////


interface Port
{
	object 	describe( string id );
};

