
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : Radar.idl
// Function         : ROVCore - Simulation Radar
/////////////////////////////////////////////////////////////////////////////////////////


interface Radar
{
	object 	describe( string id );
};

