
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : Sea.idl
// Function         : ROVCore - Simulation Sea
/////////////////////////////////////////////////////////////////////////////////////////


interface Sea
{
	string 	describe( string id );
};

