
/////////////////////////////////////////////////////////////////////////////////////////
// File name        : Timer.idl
// Function         : ROVCore - Timer service
/////////////////////////////////////////////////////////////////////////////////////////

interface Timer
{
	int			get_utc();
	int			get_tickcount();
};

