# Imported from colav_evaluation_tool
packages:
  modules:  # Land body mapping

evaluator:
  sample_interval: 2.0
  evaluate_grounding: False
  r_colregs_2_max: 4000.0 # Maximum range for COLREGS stage 2 [m]
  r_colregs_3_max: 1100.0 # Maximum range for COLREGS stage 3 [m]
  r_colregs_4_max: 200.0 # Maximum range for COLREGS stage 4 [m]
  r_pref: 190.0 # Preferred passing distance [m]
  r_min_cpa: 100.0 # Minimum acceptable passing distance at CPA [m]
  r_col_cpa: 30.0 # Distance at CPA where a collision most likely would have occurred [m]
  r_nm: 50.0 # Near miss passing distance [m]
  epsilon_d_course: 0.3 # Maneuver detection parameter, course change threshold, [deg/s] = 0.01 deg/s
  epsilon_speed: 0.2
  epsilon_d_speed: 0.05 # Detectable speed change [m/s^2]
  delta_course_app: 30.0 # Course alteration considered readily apparent [deg]
  delta_speed_app: 5.0 # Speed alteration considered readily apparent [m/s]
  delta_course_md: 2.0 # Minimum detectable course change relative to original speed
  delta_speed_md: 0.2 # Minimum detectable speed change relative to original speed
  delta_speed_reduction_app: 0.5 # Speed reduction considered apparent relative to original speed
  theta_critical_ot: 45.0 # Angle defining an overtaking situation [deg]
  theta_critical_ho: 13.0 # Angle defining a head-on situation [deg]
  theta_critical_cr: -10.0 # Angle defining a crossing situation [deg]
  theta_ot_min: 112.5 # Minimum angle defining an overtaken situation [deg]
  theta_ot_max: 247.5 # Maximum angle defining an overtaken situation [deg]
  theta_sm_lim: 10.0 # Angle defining what is considered a starboard maneuver [deg]
  alpha_ahead_cr_min: -25.0 # Lower contact angle limit defining an ahead passing in a crossing situation [deg]
  alpha_ahead_cr_max: 165.0 # Upper contact angle limit defining an ahead passing in a crossing situation [deg]
  alpha_ahead_ot_absmax: 45.0 # Absolute value of contact angle limits defining an ahead passing in an overtaking situation [deg]
  alpha_cut: 90 #
  beta_cut: 90 #
  gamma_min: 0.2 # Weight parameter on minimum acceptable range
  gamma_nm: 0.3 # Weight parameter on near miss range
  gamma_col: 0.5 # Weight parameter on collision range
  gamma_ahead_ot: 0.3 # Weight parameter defining the severity of an ahead passing in an overtaking situation
  gamma_ahead_cr: 0.5 # Weight parameter defining the severity of an ahead passing in a crossing situation
  gamma_alpha: 0.25 # Weight parameter on contact angle in pose score
  gamma_beta: 0.75 # Weight parameter on relative bearing angle in pose score
  gamma_ho_sts: 0.6 # Weight parameter defining the severity of a starboard passing in a head-on situation
  gamma_ho_nsm: 0.4 # Weight parameter defining the severity of a non-starboard maneuver in a head-on situation

  gamma_na_delta_chi: 0.5 # Weight parameter defining the severity of non-apparent course change
  gamma_na_delta_u: 0.5 # Weight parameter defining the severity of non apparent speed change (du)
  gamma_so_delta_chi: 0.5 # Weight parameter defining the severity of stand-on course change
  gamma_so_delta_u_up: 0.25 # Weight parameter defining the severity of stand-on speed increase (du_up)
  gamma_so_delta_u_down: 0.25 # Weight parameter defining the severity of stand-on speed decreases (du_down)
  gamma_c: 0.2 # Give-way compensation factor
  n_zones_gw_gr: 4 # Number of safety zones used for calculating alternative trajectories in give-way grounding

visualizer:
  show_waypoints: True
  figsize: [14, 10]
  margins: [0.0, 0.0]
  ship_linewidth: 1.7
  ship_scaling: [10.0, 14.0]
  ship_info_fontsize: 10
  ship_colors:
    [
      "xkcd:black",
      "xkcd:red",
      "xkcd:eggshell",
      "xkcd:purple",
      "xkcd:cyan",
      "xkcd:orange",
      "xkcd:fuchsia",
      "xkcd:yellow",
      "xkcd:grey",
      "xkcd:reddish brown",
      "xkcd:bubblegum",
      "xkcd:baby shit brown",
      "xkcd:khaki",
      "xkcd:cloudy blue",
      "xkcd:pale aqua",
      "xkcd:light lilac",
      "xkcd:lemon",
      "xkcd:powder blue",
      "xkcd:wine",
      "xkcd:amber",
      "xkcd:wheat",
    ]
